### ISSUE TITLE
mutation frequency criteria revision

### ISSUE THREAD

**Issue by arjunaditham** [dms-vep/RABV_Pasteur_G_DMS#15]
Currently binning naturally occurring mutants in rabies G by frequency excludes I338T, a known antigenic mutant that has been studied for prior antibodies due to its escape. 

Rather than a 0.001 frequency (requiring 7 events out of ~7000 sequences), should we consider reducing the threshold?

**Comment by Caleb-Carr** [comment]
@arjunaditham This commit (6d39a5a9ee48a381765d96a756770a71ffcdf689) adjusted the mutational frequency cutoff to be a minimum of 3 sequences. 

New plot: https://dms-vep.org/RABV_Pasteur_G_DMS/htmls/antibody_escape_vs_natural_diversity.html 
New dataframe: https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/results/natural_diversity_comparison/mutation_counts.csv
