### ISSUE TITLE
check summary plots

### ISSUE THREAD

**Issue by jbloom** [dms-vep/RABV_Pasteur_G_DMS#24]
@arjunaditham, I added summary plots that show escape and cell entry more compactly to the pipeline. They should use the same filters as everything else. They are at:
 - antibodies faceted: https://dms-vep.org/RABV_Pasteur_G_DMS/htmls/all_antibodies_and_cell_entry_faceted.html
 - antibodies overlaid: https://dms-vep.org/RABV_Pasteur_G_DMS/htmls/all_antibodies_and_cell_entry_overlaid.html

I think these look good, but can you just take a careful look and make sure they seem good in terms of the labels etc, and if so close this issue.

**Comment by arjunaditham** [comment]
The antibody plots themselves are accurate, but I have a couple of points of feedback re: labels
- the per-mutation `monoclonal antibodies escape` in the heatmap tooltip is unclear. Is that mean across all antibodies? It doesn't appear to change regardless of getting a sum, mean, etc of escape across all antibodies.
- For the antibodies overlaid, the 'individual monoclonal antibodies' are hard to navigate, especially in cases where escape sites overlap (unless I'm missing something on how to navigate that second line plot).

**Comment by jbloom** [comment]
Yes, the per-mutation monoclonal antibody escape is the average across all antibodies. This is because it is too many heatmaps to show at once. We can eventually add a legend that explains. The "sum", "mean", etc refers to how the per-mutation effects are aggregated to the site lineplots. The heatmap just shows the mean across antibodies of mutation effects, which aren't affected by how things are aggregated for sites.

I agree that the faceted plot is better, we can point people to that one if we use these.
