### ISSUE TITLE
eliminate or alter `get_filtered_CSVs` rule

### ISSUE THREAD

**Issue by jbloom** [dms-vep/RABV_Pasteur_G_DMS#25]
@Caleb-Carr, you have a `get_filtered_CSVs` rule [here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/custom_rules.smk#L8-L50).

I think you are using this to get the measurements for the Nextstrain analysis?

However, with the addition of the summaries plot, filtered CSVs with most of the same information are now created [here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/tree/main/results/summaries). Is it possible to refactor your code to use these CSVs instead? If possible, I just feel like this might be preferable as it would reduce the number of roughly redundant rules that are aggregating the data and applying the filters.

**Comment by Caleb-Carr** [comment]
Sounds good! Ill work on adjusting the nextstrain analysis to use these new files instead.
