### ISSUE TITLE
do you have code making the logo plots?

### ISSUE THREAD

**Issue by jbloom** [dms-vep/RABV_Pasteur_G_DMS#26]
@arjunaditham, in the paper draft you have code making some logo plots. Is that code somewhere I can take a look at? I think it would be ideal to integrate the logo-plot generation into the pipeline. I'm happy to do that if I know where to look for the code you are currently using.

**Comment by arjunaditham** [comment]
It is in this notebook: [240913_AntigenicSiteIII_Escape.ipynb](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/26-do-you-have-code-making-the-logo-plots/scratch_notebook/240913_AntigenicSiteIII_Escape.ipynb)

The first part of the notebook generates logo plots for sets of antibodies individually. After feedback, I added another section to identify aggregate top sites across _sets_ of antibodies and to plot accordingly. This part is for site III specifically--I would not generalize finding top sites to all antibodies in aggregate. I would only group by known target antigenic site (eg. RVC58/CR4098/RVA122/17C7, and CR57/RVC20).

If this link doesn't work please let me know. I made a separate branch called '26-do-you-have-code-making-the-logo-plots' and added the notebook `240913_AntigenicSiteIII_Escape.ipynb` with the code to make the plots in the [scratch_notebook](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/26-do-you-have-code-making-the-logo-plots/scratch_notebook/) directory. I do not see any need to merge this into main.

**Comment by arjunaditham** [comment]
@jbloom just tagging here in case, as I forgot to directly tag you to my response above. Sorry if you already saw this

**Comment by jbloom** [comment]
Great, I saw this. I am going to still prioritize looking over the cell entry parts of the data first, but then I will get to this.

**Comment by jbloom** [comment]
@arjunaditham, I added a rule that makes these escape logos.

It uses a somewhat more principled way to choose what the top sites of escape, and is easy to configure to plot things differently.

The resulting logos are in [this subdirectory](https://github.com/dms-vep/RABV_Pasteur_G_DMS/tree/main/results/escape_logos), for instance [here](https://raw.githubusercontent.com/dms-vep/RABV_Pasteur_G_DMS/refs/heads/main/results/escape_logos/region_3_antibodies.svg).

The notebook making the logos is now [rendered with the docs](https://dms-vep.org/RABV_Pasteur_G_DMS/notebooks/escape_logos.html).

We can tweak these more when we get to this part of the paper after we get the cell-entry sections nailed down.
