### ISSUE TITLE
check `dms-viz` visualizations

### ISSUE THREAD

**Issue by jbloom** [dms-vep/RABV_Pasteur_G_DMS#28]
@arjunaditham, I have added `dms-viz` JSONs as part of the pipeline.

These can be viewed at [a section near the bottom of the docs](https://dms-vep.org/RABV_Pasteur_G_DMS/).

If you provide the raw links to the JSONs (eg [here](https://raw.githubusercontent.com/dms-vep/RABV_Pasteur_G_DMS/refs/heads/main/results/dms-viz/prefusion_cell_entry.json)) to [dms-viz](https://dms-viz.github.io/) then you get interactive views, as in [here](https://dms-viz.github.io/v0/?data=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-vep%2FRABV_Pasteur_G_DMS%2Frefs%2Fheads%2Fmain%2Fresults%2Fdms-viz%2Fprefusion_cell_entry.json&sa=true).

Can you go through all six JSONs and make sure they seem correct to you in terms of putting the DMS correctly on the structures? I wanted to make these so I could look at them alongside the paper as I work on it.

Note that the one with all the antibodies (eg, [here](https://dms-viz.github.io/v0/?data=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-vep%2FRABV_Pasteur_G_DMS%2Frefs%2Fheads%2Fmain%2Fresults%2Fdms-viz%2Fprefusion_ab_escape.json&sa=true&fi=%257B%2522cell_entry%2522%253A-5%257D)) will be better once @WillHannon-MCB addresses [this issue](https://github.com/dms-viz/dms-viz.github.io/issues/97), but it is still useful now I think.

Also, it should be pretty easy to configure more of these using the YAML configuration [here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/data/dms_viz_config.yml), so either add or flag for me if you want more structures added.

Also, @Caleb-Carr, I wanted to flag this for you as well as I know you are doing a lot of Lassa antibodies. Right now I added this as a custom rule with:
 - [configuration here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/data/dms_viz_config.yml)
 - [custom rule here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/custom_rules.smk#L8-L55)
 - [notebook implementing the rule here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/notebooks/configure_dms_viz.py.ipynb) 
 
But I would like to eventually add to the pipeline. As time permits (it is not high priority), would you be interested in also trying to integrate a similar rule into your pipeline, and then somehow tracking (via this or some other GitHub issue) if it just works and if not we can try to fix in a modular way. This could be a step towards making sure it works robustly to eventually putting into `dms-vep-pipeline-3`.

**Comment by arjunaditham** [comment]
@jbloom I took a look at these and these are correct. The only point of feedback I have is that we typically have a minimum filter of `times_seen` of 2. I did not currently see that implemented (though I might have missed that). 

I think it would be possible to implement in YAML either as a limit or a filter. (I can also try doing this myself if you'd like). This is a very modest change, but it would be consistent with our prior decisions and how we typically examine the heatmap and identify escape mutants with confidence.

**Comment by jbloom** [comment]
@arjunaditham The `times_seen` filter is already implemented on mutations shown in the summary plots. That's why I was suggesting that @Caleb-Carr use those CSVs rather than the custom rules to do this filtering (see [here](https://github.com/dms-vep/RABV_Pasteur_G_DMS/issues/25)).

So the idea in the summary plots and now these `dms-viz` ones is that we have already filtered for high confidence measurements with `times_seen`, and are showing just those high-confidence values with biologically meaningful filters (eg, cell entry).
