### ISSUE TITLE
Add nextstrain tree to jbloomlab nextstrain group

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/RABV_Pasteur_G_DMS#38]
The rabies G nextstrain tree can currently only be viewed locally by uploading the json file to auspice.us, but the tree should be added to the nextstrain jbloomlab group with the associated link added to the github repo.

**Comment by jbloom** [comment]
Yes, can you prioritize this, @Caleb-Carr? That way we can put it in paper.

**Comment by jbloom** [comment]
Just wanted to re-up this issue, @Caleb-Carr

**Comment by Caleb-Carr** [comment]
Sounds good! When first attempting to upload the tree to the group, I ran into [this issue](https://github.com/nextstrain/cli/issues/409) but looks like it was just resolved so I will try again.
