### ISSUE TITLE
Confirm interactive antibody escape versus frequency plots are on main HTML display

### ISSUE THREAD

**Issue by arjunaditham** [dms-vep/RABV_Pasteur_G_DMS#39]
Here's a link to the code used to generate the interactive plot: https://github.com/dms-vep/RABV_Pasteur_G_DMS/blob/main/notebooks/natural_sequence_antibody_escape.ipynb

and a link to the plot we currently have on the landing page: https://dms-vep.org/RABV_Pasteur_G_DMS/htmls/antibody_escape_vs_natural_diversity.html

please advise if this is not what you meant in your comments on Slack

**Comment by jbloom** [comment]
Oh great. I guess you can just link to this plot directly and nothing new is needed then.

But @Caleb-Carr, can you add a selection that highlights the points (eg, with a red outline) if they are moused over?

This will be something like:
```
selection_mutation = alt.selection_point(on="mouseover", empty=False, fields=["mutation"])

(
  <chart>
  .add_params(selection_mutation)
  .encode(
    ...
    strokeWidth=alt.condition(selection_mutation, alt.value(2), alt.value(0)),
  )
  .mark_circle(..., stroke="red")
)
```

**Comment by jbloom** [comment]
@Caleb-Carr, can you also modify the Tooltip (eg, `Tooltip("frequency", format=".3g")`) to show a reasonable number of significant digits on the mutation frequencies. Right now it has more than a dozen digits.
