### ISSUE TITLE
Update dms-vep-pipeline-3

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/RABV_Pasteur_G_DMS#41]
The current `dms-vep-pipeline-3` is using `multidms 0.3.3` which had the [following issue](https://github.com/dms-vep/dms-vep-pipeline-3/issues/158). It might be worthwhile to update the core pipeline which updates `multidms` to `0.4.0` because this library is mostly single mutants?

**Comment by jbloom** [comment]
I am not sure this is worth doing as the shifts in measurements are small, but we can consider. But if so, let's wait until I have cut another stable version of `dms-vep-pipeline-3`.

So let's keep this issue open for now but not doing anything yet.

**Comment by jbloom** [comment]
I'm going to close this as I don't think we have to update pipeline at this point, current version was still pretty good and this would require remaking all figures.
