### ISSUE TITLE
Clean and update scratch_notebook directory 

### ISSUE THREAD

**Issue by arjunaditham** [dms-vep/RABV_Pasteur_G_DMS#45]
`scratch_notebook` directory needs to be cleaned up and notebooks (eg. for identifying antibody-rabies G contacts) need to be added.

**Comment by jbloom** [comment]
@arjunaditham, can the `scratch_notebook` subdirectory be moved to subdirectories of `non-pipeline_analyses`? You can organize different subdirs for different types of analyses. That way we will just have one subdirectory for such analyses.

**Comment by arjunaditham** [comment]
Yes, I can go ahead and move them there upon cleaning the `scratch_notebook` directory. I am making sure I have all of the notebooks I used to generate figures annotated and labeled before committing anything or making any pull requests. 

I put this on the back burner when making figure revisions but will return to this ASAP.

**Comment by arjunaditham** [comment]
I've gone ahead and pushed this into a separate branch. This branch also has moved the notebooks into non-pipeline_analyses
