### ISSUE TITLE
'Null' sites on antibody escape mutation frequency plots

### ISSUE THREAD

**Issue by arjunaditham** [dms-vep/RABV_Pasteur_G_DMS#49]
On this plot https://dms-vep.org/RABV_Pasteur_G_DMS/htmls/antibody_escape_vs_natural_diversity.html for the antibody escape versus diversity, some points have 'null' sites (screenshot example below). 

It's not really clear why this is caused. Can this be checked?

<img width="283" alt="Screenshot 2024-12-07 at 11 00 37 AM" src="https://github.com/user-attachments/assets/fc980e25-4bfe-4888-84dd-0ef83f40f910">

**Comment by Caleb-Carr** [comment]
I think this might be related to issue #50

**Comment by jbloom** [comment]
@Caleb-Carr, can you just re-assign site and sequential site for these by merging any sites with null identities with a data frame mapping `natural_sequence_site` to `site` and `sequential_site`?

**Comment by Caleb-Carr** [comment]
@jbloom I will make sure that the sites are correctly labeled but related to issue #50 these sites that are showing up as "null" seem to be the ones with very low functional scores (about -7). Is that okay to keep in these plots or should they be filtered with the -5 default?

**Comment by jbloom** [comment]
I think we should keep them. The rationale for filtering those in heatmaps and most displays is that they are highly deleterious and should not be relevant. But clearly if these are present, then in some cases there is enough epistasis to include them so we should probably show them if they are in natural sequences.
