### ISSUE TITLE
Potential issue in filtering data in `summaries`

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/RABV_Pasteur_G_DMS#50]
Based on my understanding, the summaries directory contains the filtered data to match the defaults from the antibody escape plots? However, it seems to be including some mutations with low functional scores (-7) even though the default is -5. 

Image of 17C7 antibody escape plot:
<img width="147" alt="Screenshot 2024-12-07 at 11 16 14 AM" src="https://github.com/user-attachments/assets/c9d1651b-8fbc-4604-9552-f7d86afd6ef6">

Image from summaries at same region with the N361 mutations highlighted:
<img width="356" alt="Screenshot 2024-12-07 at 11 15 52 AM" src="https://github.com/user-attachments/assets/f7324566-a700-4981-823b-f3e803f1fa0b">

**Comment by jbloom** [comment]
I think this is OK, isn't it? In the summary plot, these mutations are not removed (as are sites with low `times_seen`), they are just filtered from the default display but should still be in the data as they can be recovered in the heatmap by adjusting the slider.

In general this should not be a big problem as mutations with very low cell entry scores should not be common among natural strains.

**Comment by Caleb-Carr** [comment]
Sounds good! Closing this issue
