### ISSUE TITLE
problem building VitePress homepage

### ISSUE THREAD

**Issue by jbloom** [dms-vep/RABV_Pasteur_G_DMS#54]
@WillHannon-MCB, can you help with this? It builds locally and previews just fine.

But I get the following error during deployment: https://github.com/dms-vep/RABV_Pasteur_G_DMS/actions/runs/12258659817

Note one message is about the node version being outdated, should that be fixed in the deployment YAML? But I'm not sure if that is the cause of the underlying error.

**Comment by WillHannon-MCB** [comment]
@jbloom, I think I tracked down the issue.

In Javascript, you can use `require(some_function)` _or_ `import some_function from a_library` to use external code in a file. The `import` syntax is newer and preferred by most. Annoyingly, different Node versions expect different syntax by default. Later versions are better at resolving conflicts automatically.

We can add `type: module` to `package.json` to specify that Node should expect the `import` syntax:

```json
{
  "type": "module",  //<--- add this line
  "scripts": {
    "docs:dev": "vitepress dev homepage",
    "docs:build": "vitepress build homepage",
    "docs:preview": "vitepress preview homepage",
    "remote:docs:dev": "vitepress dev homepage --host 0.0.0.0 --port $(fhfreeport)"
  },
  ...
  ```
  
Can you grant me permission to make a new branch on this repo?

**Comment by jbloom** [comment]
Giving you that permission now. 

Can you also check if we should be updating the `ubuntu` version referred to w regard to the other warning, even if that is not the cause of this error? If you can make a pull request fixing these issues, I can then make the same changes into the prototype example in `dms-vep-pipeline-3`.
